[tool.poetry]
name = "streetfigthergpt"
version = "0.1.0"
description = ""
authors = ["felipec <felipecmelo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

